### ISSUE TITLE
Trying to run the template on an Oculus Quest 2

### ISSUE THREAD

**Issue by alexradunet** [jtnicholl/godot4-vr-physics-template#1]
Hello,

I am trying to get this template to work with the Oculus Quest Touch Controller ( Oculus Quest 2 with AirLink for now ) and I am encountering issues getting it to work.

Here is my repo that uses this template ( https://github.com/alexradu95/CicodotLaboratory )

Steps that I tried to make it work :

Step 1 : Update Action Map for Touch Controllers 

<img width="503" alt="image" src="https://user-images.githubusercontent.com/15926861/211303488-8cb1a2a3-a47c-4aa2-8ce3-f2cd1dc94f81.png">

Step 2:  Duplicated vive_controller and Updated the _DEFAULT_CONTROLLER_SETTINGS
<img width="822" alt="image" src="https://user-images.githubusercontent.com/15926861/211304330-50cdab94-fb59-4ab1-aec5-cef3a26c7ad9.png">

Result :

As of now, the hands do not sync with the controller movement, and after turning a few seconds sometimes the game freezes with the following error:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/15926861/211304599-f348dcb1-ec50-4bcb-8d9e-2405901d9908.png">

Here is a display capture :

1. The hands don't move when I move the controller
2. No animations are played when pressing grib button or trigger button
3. Only turning works with no problem.

[screen-capture (2).webm](https://user-images.githubusercontent.com/15926861/211306304-1ab7e832-0526-40c1-a9fa-93828142b24e.webm)

End goal: 
Make this template work with Oculus Quest 2 and Oculus Controllers and create a small guide to help future developers.

**Comment by jtnicholl** [comment]
The hands don't have any grip animations added yet, and the freezing is something I've noticed a few times as well, I suspect it may be because either the physics engine or renderer are set to multithreaded. I'll test it out later and open an issue on Godot's repo later if I can figure it out.
As for the hands not moving, though, I'm not sure. They do seem to be moving _some_, so I don't suspect it's an issue with pose binding. There is an issue where the hands don't track while you're turning, I wonder if this is related. (Maybe you're always turning, just too small an amount to notice.) Could you test if the XRController nodes are moving, or if it's just the hand nodes?

**Comment by jtnicholl** [comment]
The project now provides bindings for the Touch Controllers. I've also fixed the lack of grip animations, the hands not moving while turning, and the random freezing.
Looking at your video again, I noticed the teleporter target isn't moving either. The teleporters are parented to the controllers, not anything driven by physics, so I think there was a tracking issue on your end. If so, I don't know how to help with that.

Since I've addressed everything I can that was brought up here, I'm closing this. If you run into more problems feel free to open another issue.
